### PR TITLE
(WIP) initial try of using sphinx generate API doc

### PR DESCRIPTION
**Pull request by fhh2626**
I tried to use sphinx to generate the API doc, most of warnings have been addressed. However, there are still three issues.

- [x] Sphinx cannot find version.py
- [x] The generated htmls are ugly. At very least, there should be emply lines between class methods
- [ ] I cannot include README.md in the index.rst (through either m2r or myst-parser)

@HanatoK can you have a look?

### CODE REVIEW

**Review by HanatoK — CHANGES_REQUESTED** [review]
I suggest to move the documentation files out of the source directory to fhh2626/BFEE2/doc, and redirect the users to an online documentation in GUI. Most python projects (you can take a look at MDAnalysis and pymol) do not bundle the documentation within their distributions.

**Review by HanatoK — CHANGES_REQUESTED** [review]
I suggest to move the documentation files out of the source directory to fhh2626/BFEE2/doc, and redirect the users to an online documentation in GUI. Most python projects (you can take a look at MDAnalysis and pymol) do not bundle the documentation within their distributions.

**Comment by fhh2626** [comment]
What about this version? And there is still 1 warning?

**Comment by fhh2626** [comment]
Looks nice. Thanks. 
Only one more question. After you re-write README.md in the RST format, do we need to change index.rst every time when we change README.md?

**Comment by HanatoK** [comment]
@fhh2626 
I think so. There must be some ways to keep them synchronized. We can do that in the future.

**Comment by fhh2626** [comment]
> @fhh2626
> I think so. There must be some ways to keep them synchronized. We can do that in the future.

I think there is some way to embed README.md in a RST file, but the current version is good enough. I will merge it.

**Pull request merged**
