### PR TITLE
Use sphinx to generate documents automatically.

### PR DESCRIPTION
**Pull request by HanatoK**
This PR is the first attempt to generate sphinx documentations from python docstrings.

### CODE REVIEW

**Comment by HanatoK** [comment]
Sphinx example:
https://eikonomega.medium.com/getting-started-with-sphinx-autodoc-part-1-2cebbbca5365

**Comment by fhh2626** [comment]
I recently reformatted all the docStrings, trying to make things easy to generate documents automatically. Could you let this PR adapt the dev branch?

**Comment by HanatoK** [comment]
@fhh2626 
Done but still there are lots of warnings.

**Comment by fhh2626** [comment]
I have created a new PR #54 .

**Review by HanatoK — COMMENTED** [review]
I suggest to move the documentation files out of the source directory to `fhh2626/BFEE2/doc`, and redirect the users to an online documentation in GUI. Most python projects (you can take a look at MDAnalysis and pymol) do not bundle the documentation within their distributions.

**Pull request closed without merging**
